### ISSUE TITLE
Parsing data file: line endings, various OSs

### ISSUE THREAD

**Issue by jbrgfx** [omgneering/elhex_delivery#1]
Excellent videos!
There is an easy to fix bug when run under Windows.

The tests all pass when run under Linux, but eight fail under Windows -- all eight failures relate to way various OSs treat the line endings in a data file.

Solved by replacing Unix specific implementation of split on line 5 of 
elhex_delivery/lib/postal_code/data_parser.ex
with a regular expression that handles both "\n" and "\r\n" style lines endings:

        # [_header | data_rows] = File.read!(@postal_codes_filepath) |> String.split("\n")
 [_header | data_rows] = File.read!(@postal_codes_filepath) |> String.split(~r/\R/)

**Comment by mkompanets** [comment]
Thank you @jbrgfx will add this momentarily
